# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
# NOTE: temporarily using grst fork of `r-appveyor`, until
#   download.file problem is fixed upstream. See
#   https://github.com/krlmlr/r-appveyor/issues/153.
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/grst/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    R_REMOTES_STANDALONE: true
    platform: x64
    PKGTYPE: "win.binary"
    GITHUB_PAT:
      secure: Xl3cNXsF+tbyVRLHb28x2q3KmLnrZx1sXRZV5LAJ7uye1ymXhbMQYNuTses3GB0N

  matrix:
  - R_VERSION: 3.6.2
    R_ARCH: x64

  - R_VERSION: 3.5.1
    R_ARCH: x64

# XML package does not compile on appveyor, remotes does not use (a little older) binary version. 
# Disable R 3.4.1 until this is fixed. 
#  - R_VERSION: 3.4.1
#    R_ARCH: x64

matrix:
  fast_finish: true
